# Generated by Django 4.2.11 on 2026-05-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_add_owner_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='category',
            field=models.CharField(choices=[('work', 'Work'), ('personal', 'Personal'), ('urgent', 'Urgent'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2),
        ),
    ]
